### ISSUE TITLE
h2o-3-coxph-pretransformer does not appear in the transformers list after adding it.

### ISSUE THREAD

**Issue by fousasg** [h2oai/driverlessai-recipes#123]
h2o-3-coxph-pretransformer does not appear in the transformers list in experts settings in recipes tab, after adding it from https://github.com/h2oai/driverlessai-recipes/blob/rel-1.9.0/transformers/survival/h2o-3-coxph-pretransformer.py

**Comment by grigory93** [comment]
Greg @fousasg it works on prerelease:

<img width="1397" alt="Screen Shot 2020-12-16 at 14 43 45" src="https://user-images.githubusercontent.com/5093758/102404553-7df48100-3fad-11eb-9d9a-189d340f1f30.png">

<img width="1591" alt="Screen Shot 2020-12-16 at 14 44 23" src="https://user-images.githubusercontent.com/5093758/102404547-7cc35400-3fad-11eb-902a-095a62fb72e0.png">
