### ISSUE TITLE
driverless h2oai text_embedding_similarity_transformers.py doesnt show up

### ISSUE THREAD

**Issue by cyrilthank** [h2oai/driverlessai-recipes#19]
I am using the 21 day trial driverless h2oai

I am trying to upload custom recipe (text_embedding_similarity_transformers.py) for transform

after the save it doesnt show up as mentioned in the blog for similar use case

https://www.h2o.ai/blog/custom-machine-learning-recipes-the-ingredients-for-success/

can you please advise what i am doing wrong as i am trying to ascertain whether the bert embedding is used or not

**Comment by cyrilthank** [comment]
![image](https://user-images.githubusercontent.com/4562436/63828994-d9000000-c985-11e9-95d4-57a8b2dcb98d.png)

**Comment by SudalaiRajkumar** [comment]
HI @cyrilthank - Currently this transformer is disabled by default in the [code](https://github.com/h2oai/driverlessai-recipes/blob/master/transformers/nlp/text_embedding_similarity_transformers.py#L20). This is because of the GPU memory issue mentioned in #6. Thank you.

**Comment by cyrilthank** [comment]
Thanks a lot @SudalaiRajkumar  for the clarification. Thank you

Cyril

**Comment by cyrilthank** [comment]
Can you please also advise if there are any additional steps to be done to specifically enable  the BERT?
Thank you Cyril 
    On Wednesday, August 28, 2019, 12:38:55 PM GMT+5:30, SudalaiRajkumar <notifications@github.com> wrote:  
 
 
HI @cyrilthank - Currently this transformer is disabled by default in the code. This is because of the GPU memory issue mentioned in #6. Thank you.

**Comment by SudalaiRajkumar** [comment]
You could enable the recipe in code and use it but you _may_ face some GPU memory issues.
