### ISSUE TITLE
Queries with custom recipes via BYOR

### ISSUE THREAD

**Issue by josiahsams** [h2oai/driverlessai-recipes#24]
After trying out custom recipes with H20.DAI, I’m having the following queries,

1. After uploading the recipe, is there a way for customers to modify the parameters specially the ones we set in fn. set_default_params ?

2. Regarding mutate_params, when does it get triggered ?

3. After uploading a recipe, is there a way to delete user uploaded recipe ?

4. Can we control the number of GPUs to be utilized for an experiment ?

5. There are some keywords like genes all over the logs. Where can be get details about these terminologies ?

**Comment by kaz-Anova** [comment]
1.  Yes. Through `mutate_params` that you pointed it out in your 2nd questions.

For example, in https://github.com/h2oai/driverlessai-recipes/blob/master/models/algorithms/extra_trees.py m you can see that in   `mutate_params` 

you see this snippet of code:

```
    def mutate_params(self, accuracy=10, **kwargs):
        if accuracy > 8:
            estimators_list = [100, 200, 300, 500, 1000, 2000]
        elif accuracy >= 5:
            estimators_list = [50, 100, 200, 300, 400, 500]
        else:
            estimators_list = [10, 50, 100, 150, 200, 250, 300]
        # Modify certain parameters for tuning
        self.params["n_estimators"] = int(np.random.choice(estimators_list))
```

This essentially says, when accuracy is higher than 8, consider this list of potential `n_estimator`(e.g. trees) in the genetic algorithm-based hyper parameter search

2. `mutate_params` is called in every iteration during the feature evolution and modelling phase - when we search for the best features and best models and models' hyper parameters. You can think of this as a `grid-search`. This is linked with out genetic algorithm. To understand what our genetic algorithm is, you may have a look in the following presentation , after 25:15 : https://www.youtube.com/watch?v=GMtgT-3hENY&t=1525s

3.  You can  deselect the recipe, via "unchecking", the transformer, model or scorer (whichever one is represented by the recipe ) from inside the EXPERT SETTINGS - see image:

![image](https://user-images.githubusercontent.com/7644911/64524661-ec508b00-d2f6-11e9-85d4-1fa6fbfd7516.png)

Every time you upload one with the same name , it will replace the old one. 


4. Yes , from the EXPERT SETTINGs you can set number of GPUs via experiment : 

![image](https://user-images.githubusercontent.com/7644911/64524770-2e79cc80-d2f7-11e9-81a5-6d061538bb22.png)

5. Our documentation is a good way to start (http://docs.h2o.ai/driverless-ai/latest-stable/docs/userguide/index.html)  . You can just type in the keyword. Specifically about the genes, these are linked with our genetic algorithm (see the video link I shared above). In every iteration Driverless selects from a pool of potential models and features to evaluate them and decide which ones are best. This pool of individual transformers/models are called genes and have the potential to evolve over time and become more specific and fine-tuned on the specific dataset.

**Comment by josiahsams** [comment]
Thanks @kaz-Anova for the inputs.
