### ISSUE TITLE
Modify ENV variables in custom recipes

### ISSUE THREAD

**Issue by josiahsams** [h2oai/driverlessai-recipes#31]
During our exploration of BYOR, one of our Models is dependent on numba. We included this dependency under the respective class as follows,
```
_modules_needed_by_name = ["numba"]
```
While uploading this recipe, pip installation of numba fails as it requires LLVM compiler installation. Since we had the LLVM compiler installation in a user-defined location, pip fails to pick up relevant binaries like `llvm-config` from these custom locations. 

So Is there a way to provide ENVIRONMENTAL variables like, `export PATH=$PATH:/opt/llvm/bin`,  along with the recipes so that these variables get alive during the recipe deployment time ?

**Comment by pseudotensor** [comment]
Can you set `os.environ['YOUR_ENV_VAR'] = "YOUR_VALUE"` ?

**Comment by josiahsams** [comment]
I'm not sure how the ENV set in my recipe will get picked up during the `pip` installation by DAI.

I've made the following changes to my recipe,
```
os.environ['PATH'] = os.environ['PATH']+"/opt/llvm/bin"

_global_modules_needed_by_name = ["numba==0.45.1"]  
```

Still I get the llvm related binaries are not found in my errlog under, `/opt/h2oai/dai/tmp/contrib/env/pip_install_numba.71e57316-34ac-4032-8f3f-eb3686a65d29.log`,

```
2019-09-18T09:32:20     NotADirectoryError: [Errno 20] Not a directory: 'llvm-config'
```
